add device code flow for MSAL
equinor/osdu-sdk-python pull request #16
Opened 2023-04-13 10:52 UTC by adamchengtkc

Device code flow allows auth without browser install on the client. e.g. codespace

`OsduMsalInteractiveCredential(...,devicecodeflow=True)`

MSAL device code flow
https://github.com/Azure-Samples/ms-identity-python-devicecodeflow

2023-04-13 11:00 UTC, john-haugland reviewed
Can you check  if "user_code" in flow before using it ?

2023-04-13 11:04 UTC, tahir-so reviewed
I suggest adding a new class.

2023-04-14 09:04 UTC, adamchengtkc commented
OsduMsalDeviceCode(...)
No breaking change

2023-04-19 13:20 UTC, adamchengtkc commented
Added on-behalf-of flow and bumped version

2023-05-09 11:24 UTC, mahewitt requested changes
Looks good bar the requested naming change for consistency with other Credentials

2023-05-09 11:24 UTC, mahewitt commented on src/osdu/identity/_credential/msal_interactive.py
> +class OsduMsalDeviceCode(OsduMsalInteractiveCredentialBase):
For consistency should be OsduMsalDeviceCodeCredential

2023-05-09 11:24 UTC, mahewitt commented on src/osdu/identity/_credential/msal_interactive.py
> +class OsduMsalOnBehalfOf(OsduBaseCredential):
For consistency should be OsduMsalOnBehalfOfCredential

2023-06-27 09:44 UTC, ErlendHaa commented
Hi! Any news on this? Device flow would be really useful :)

2023-11-05 19:29 UTC, closed without merging